---
title: "meta_analysis_sigfit_10samples_allSDS8_buccal_Dec2021_SDS"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache=TRUE, fig.path="./graphics/plot",autodep=TRUE,fig.width=5, fig.height=4)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(caTools)
library(reshape2)
library(dplyr)
library(hdp)
location="local"

if (location=="farm"){
  root="/lustre/scratch117/casm/team154/hm8/SDS"
} else if (location=="local"){
  root="/Users/hm8/volumes/hm8_scratch117/SDS"
} else {
  warning("location not set- using current directory")
  root=getwd()
}
```


# Load in each individual dataset
```{r, message=FALSE, warning=FALSE}
groupname = "SDS10_allSDS8_buccal_sigfit"
burden = read.table("../data/burden_by_sample.txt", header=T, stringsAsFactors = F, sep="\t")
```




# Initial assessment of sigfit results
```{r, message=FALSE, warning=FALSE}
# Load in hdp analysis object
# This is after componenet extraction
load(file="../data/xposures_SDS10_allSDS8_buccal.sigfit.chain1.Rdata")
sig_prop = exposures$mean
sig_prop$colony = rownames(sig_prop)
sig_prop_type = merge(burden, sig_prop, by="colony")
#save(sig_prop_type, file=paste("sig_prop_type.", groupname, ".Rdata", sep="") )
```


## For stacked barplot
```{r, message=FALSE, warning=FALSE}
sig_prop_type_stack = sig_prop_type #[,c(1,3,7,11,13:ncol(sig_prop_type))]
sig_prop_type_stackO = sig_prop_type_stack[order(sig_prop_type_stack$nsub_adj, decreasing = FALSE),]
#sig_prop_type_stackO$samp_names = apply(sig_prop_type_stackO, MARGIN=1, FUN=function(X)  paste(X[1], X[3], sep = "_"))
sig_prop_type_stackO$colony = factor(sig_prop_type_stackO$colony, levels=unique(sig_prop_type_stackO$colony) )
sig_prop_type2_stack = melt(sig_prop_type_stackO[,c("colony", "age_at_sample_exact","internal_id", "nsub_adj", "SBSblood", "SBS1")], id.vars=c("colony", "age_at_sample_exact","internal_id", "nsub_adj")) # not unattributed
#sig_prop_type2_stack$Donor_Age = paste(sig_prop_type2_stack$Donor, sig_prop_type2_stack$Age, sep=": ")
sig_prop_type2_stack$Donor = factor(as.factor(sig_prop_type2_stack$internal_id), levels = levels(as.factor(sig_prop_type2_stack$internal_id))[c(1,3:10,2)] )

my10 = brewer.pal(10, "Set1") 
my_colors = c(my10[2:9],"red","black","lightblue","white") # Cosmic analysis
ggplot(subset(sig_prop_type2_stack), aes(x=colony, y=value, fill=variable)) +
  geom_bar(stat="identity") +
  facet_wrap(.~Donor, scales = "free_x", nrow=2)+
  xlab("") +
  ylab("Proportion per genome") +
  scale_fill_manual("",values=my_colors)+
  #scale_fill_manual("",values=my_colors, labels=c("Sblood","S1","S9","S8","S7","S17","N2","N3","ns") ) +
  theme_light() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x=element_blank(),
        #axis.text = element_text(size = 10),
        axis.line.x=element_blank(),
        #legend.justification=c(1,0), legend.position=c(1,0.5),
        #panel.spacing = unit(1, "lines"),
        strip.text = element_text(size = 14),
        strip.text.x = element_text(margin = margin(.1, 0, .1, 0, "cm")) )
ggsave(file=paste("signatures_", groupname, "_stackedBar_Prop_names.pdf", sep=""), width=9,height=6)



ggplot(subset(sig_prop_type2_stack), aes(x=colony, y=value, fill=variable)) +
  geom_bar(stat="identity") +
  facet_wrap(.~Donor, scales = "free_x", nrow=1)+ 
  xlab("") +
  ylab("Proportion") +
  scale_fill_manual("",values=my_colors)+
  theme_light() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x=element_blank(),
        axis.line.x=element_blank(),
        strip.text = element_text(size = 10,colour = 'black'),
        strip.background.x =element_rect(fill="white"),
        strip.text.x = element_text(margin = margin(.1, 0, .1, 0, "cm")) )
ggsave(file=paste("signatures_", groupname, "_stackedBar_Prop_names_1row.pdf", sep=""), width=12,height=2)
```

## For stacked barplot: absolute #s
```{r, message=FALSE, warning=FALSE}
sig_prop_type_stack_N = cbind(sig_prop_type[,c(1:8)],
  sig_prop_type[,9:10] * sig_prop_type$nsub_adj)
sig_prop_type_stackO = sig_prop_type_stack_N[order(sig_prop_type_stack_N$internal_id, sig_prop_type_stack_N$nsub_adj) ,]
sig_prop_type_stackO$colony = factor(sig_prop_type_stackO$colony, levels=unique(sig_prop_type_stackO$colony) )
sig_prop_type2_stack = melt(sig_prop_type_stackO[,c("colony", "age_at_sample_exact","internal_id", "nsub_adj", "SBSblood", "SBS1")], id.vars=c("colony", "age_at_sample_exact","internal_id", "nsub_adj"))
sig_prop_type2_stack$Donor = factor(as.factor(sig_prop_type2_stack$internal_id), levels = levels(as.factor(sig_prop_type2_stack$internal_id))[c(1,3:10,2)] )

ggplot(subset(sig_prop_type2_stack), aes(x=colony, y=value, fill=variable)) +
  geom_bar(stat="identity") +
  facet_wrap(.~Donor, scales = "free_x", nrow=1)+ 
  xlab("") +
  ylab("# SNVs per genome") +
  scale_fill_manual("",values=my_colors)+
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x=element_blank(),
        #axis.text = element_text(size = 10),
        axis.line.x=element_blank(),
        #legend.justification=c(1,0), legend.position=c(1,0.5),
        #panel.spacing = unit(1, "lines"),
        strip.text = element_text(size = 10,colour = 'black'),
        strip.background.x =element_rect(fill="white"),
        strip.text.x = element_text(margin = margin(.1, 0, .1, 0, "cm")) ,
        panel.grid.major.x = element_blank() ,
        panel.spacing = unit(0.1, "lines"),
        panel.border = element_rect(fill=NA, colour = "black", size=0.2) )
ggsave(file=paste("signatures_", groupname, "_stackedBar_Num_names_1row.pdf", sep=""), width=7,height=1.5)
```

